### ISSUE TITLE
Feature Request: Allow configuration of scanning reports output

### ISSUE THREAD

**Issue by nnelas** [kubewarden/audit-scanner#102]
### Is your feature request related to a problem?

Hallo! 👋 

I'm currently analysing the hypothesis of using the Kubewarden stack as the policy manager for a multi-tenant cluster, and I'm struggling a bit with `audit-scanner` as it requires by default the instances of a (Cluster)PolicyReport for `PolicyReportStore`. From our experience with Gatekeeper, working with clusters with hundreds of namespaces, all these CRD instances led to increased pressure on `apiserver` and `etcd` nodes, which if possible would be something we would want to avoid.

### Solution you'd like

As a result, I would like to understand if it would be possible to add a configuration that would define where would `audit-scanner` output/write a scanning report. To keep compatibility, it could keep writing to a (Cluster)PolicyReport by default. It could also output as JSON to the stdout (just like the `--print` flag that you currently have) or even write to a file on a volumeMount.

### Alternatives you've considered

Looking at `audit-scanner` source-code, I couldn't find any alternative without changing its source code.

### Anything else?

Please let me know if this makes sense and if it's aligned with the vision that you have for `audit-scanner`. I can also happily contribute with a PR, if this is something that you can't fit in your roadmap in the foreseeable future.

Thank you so much for all the hard work that you've put into this project! 🙌

**Comment by viccuad** [comment]
Hi, thanks for opening this feature request!

> Please let me know if this makes sense and if it's aligned with the vision that you have for audit-scanner. 

We share the same concerns about instantiating PolicyReports WRT to `etcd` and `apiserver` in bigger clusters.

In fact, we have had this in mind since the audit-scanner feature inception, you can have a look at its RFC here, particularly:
    https://github.com/kubewarden/rfc/blob/main/rfc/0012-policy-report.md#drawbacks
    https://github.com/kubewarden/rfc/blob/main/rfc/0011-audit-checks.md#drawbacks

So that is good news :).

For developing and testing, we provide the PolicyReport as JSON in the logs with `--print`. This has the drawback that a badly log message from a warning or an error may not be JSON formatted, hence the whole audit-scanner logs may not be JSON messages, and therefore may need user parsing when consuming it. So far we have taken care that is not the case, but it is not easily implemented or tested.

Other options we have considered is providing an HTTP endpoint that serves the results, and saving the results to an in-cluster database instead of etcd. The idea of writing to a file on a volumeMount is new to me, and is also another possible option. Personally, it feels a bit overkill to add a volumeMount just for that, though. I wonder what @kubewarden/kubewarden-developers  think.

WRT to your hyphotesis on using Kubewarden, do you already have other tools in mind to consume this JSON-formatted info? do you have a preferred way of consuming the JSON? We would be happy to serve the JSON in a useful way.

**Comment by viccuad** [comment]
The more I think about writing to a provided VolumeMount, the more I think it's the simpler way for now. The user provides the VM, and in audit-scanner we can ensure we only write the PolicyReport JSON once there has been a successful run, hence the VM always contains the last known state of the audit. One needs to consider making writing to the VM file concurrent safe in case there are several audit-scanner jobs, that started at different times. It may be enough with timestamping the beginning of the file contents.

**Comment by flavio** [comment]
> **Semi-OT:** @nnelas we are glad you're looking into Kubewarden. Please don't hesitate to reach out to us. You can find us on Slack, we've also our monthly meeting on Zoom coming up. You can find all the links on our [homepage](https://kubewarden.io).

As Victor said, we share your concerns about the performance impact of storing the policy reports into etcd. We want to offer alternatives to this approach in the next iteration of the audit-scanner. Your feedback would allow us to determine the direction to pursue.

Do you already have plans about how to leverage the json output? Do you plan to rely on some centralized logging solution to handle that?

**Comment by nnelas** [comment]
Hallo @viccuad and @flavio ! 👋 

Thank you so much for your comments, they are really insightful (and I'm glad that this is something that you already thought about)! 

I've been discussing this internally with one of my co-workers (tagging @brunorene for visibility), and we think that there's a way to suit our needs without much of a hassle. To summarise, we would like to use `audit-scanner` to provide condensed cluster status with the help of metrics for Grafana dashboards and more detailed information available through logs with ElasticSearch. As such, we think that we can achieve that with 2 things: metrics and audit logs. 

Given that the remaining Kubewarden projects are integrated with OpenTelemetry, perhaps we could leverage it to expose metrics at the namespace level, like `policy-server` already does with `kubewarden_policy_evaluations_total`.

Regarding logs, we were wondering if it would be possible to log each `namespaces[].results[]`, as this would include relevant information for us (like the affected namespace, the non-compliant resource and the policy that it violated), which we would then use to index into ElasticSearch, which our tenants could use to query more information about their namespace. 

Also, keeping in mind that these new developments could take some time to be implemented, would you be happy for us to contribute with a PR to disable (Cluster)PolicyReport per configuration?

Hope this gave you more context about our goals with `audit-scanner`. Please let us know if there's anything else we can help you with, both I and the remaining engineers from my team are happy to contribute and keen to see Kubewarden thrive!

Thank you! 🙌

**Comment by jvanz** [comment]
> > @jvanz , just realized that the [PR for the audit-scanner docs](https://github.com/kubewarden/docs/pull/199) doesn't mention the new instrumentation, could you add a small paragraph there? (as the PR branch is on your personal repo)
> 

Done. https://github.com/kubewarden/docs/pull/199#issuecomment-1708403966
