### ISSUE TITLE
audit-scanner: Check ObjectSelector/LabelSelector

### ISSUE THREAD

**Issue by viccuad** [kubewarden/audit-scanner#54]
Per RFC, before running the audit scan of a Policy against a Resource, we should check that the Resource passes the evaluation against the policy spec.ObjectSelector.

### Acceptance criteria

Evaluate the Policy [`spec.ObjectSelector` ](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#LabelSelector) against the resource under audit. If it ends up being skipped, skip the resource from auditing.
We have unit tests
We have integration test if needed

**Comment by jvanz** [comment]
I think this change is not required anymore. Considering that we use the resource's [objectReference](https://github.com/kubewarden/audit-scanner/blob/bea36e08f9b00c4f9e30b1303f3f2b22ca577c6d/internal/report/report.go#L233) to check if we can reuse the previous result, I believe that this objectSelector check is not necessary anymore. Because if any change to the resource happens the objectReference, which include the resource's `resourceVersion`, will not match. Thus, I new evaluation will be perform. Otherwise, the old result will be reuse.

What do you think @kubewarden/kubewarden-developers

**Comment by viccuad** [comment]
I think this change still is needed for behaviour parity with normal policy evaluations. We need to check that the policy indeed applies to the resource because of the `[spec.ObjectSelector](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#LabelSelector)`. For example, a ClusterAdmissionPolicy can specify the ObjectSelector so only resources that have a label `prod` are evaluated, and that is ortogonal to checking the objectReference resourceVersion or the policy resourceVersion.

**Comment by jvanz** [comment]
Thinking more about this, I agree. We need to consider the `ObjectSelector` to evaluate the resources. However, I think we can use it in a different place. Instead of using to decide if we need to skip or not the evaluation, we can use it to fetch the relevant resources only. The [list](https://pkg.go.dev/k8s.io/client-go/dynamic#ResourceInterface) method allow us to define some option to filter resources. This makes more sense to me. Because we avoid iterate over a bunch of resources that should not be evaluated anyway.
