### ISSUE TITLE
Consume policy-server endpoint certs in audit-scanner

### ISSUE THREAD

**Issue by viccuad** [kubewarden/audit-scanner#64]
For each policy-server that the audit-scanner hits on `audit/` endpoint [here](https://github.com/kubewarden/audit-scanner/pull/62/files#diff-95e0a286796962f784af743a32471dada7258c4789b441aaca0a77653e3c1155R294-R295), it should do so over https.

Right now, the cert for the policy-servers endpoints is being generated by the kubewarden-controller [here](https://github.com/kubewarden/kubewarden-controller/tree/9310e65fb4ddcf0000dc62738003ac247fa6e6d8/internal/pkg/admission/reconciler.go). This means that the cert is not created until after the controller has reconciled the policy-server. The audit-scanner must somehow obtain the cert just in time, as it must not need redeploy if there are new policy-servers with auditable policies.

### Acceptance criteria

- For each policy-server, consume its CA or cert.

**Comment by flavio** [comment]
I don't know why, but the link to the code inside of the issue does not work.

However, I looked more into the `kubewarden-controller` code and I can confirm that:
* We have a unique self-signed certificate authority (CA). There's a Kubernetes secret called `policy-server-root-ca` that has the following contents:
  * `policy-server-root-ca-pem`: the PEM-encoded CA
  * `policy-server-root-ca-cert`: the DER-encoded CA
  * `policy-server-root-ca-privatekey-cert`: the private key of the CA, I think it's DER encoded
* Each policy server instance has its own certificate, which is always issued by the central CA

Because of that, we need to inject into the `audit-scanner` only the certificate of our CA. Basically we have to project the contents of `policy-server-root-ca.policy-server-root-ca-pem` (the Kubernetes secret) into the container that runs the audit-scanner.
The Go code has to be extended to add this CA to the process [`CertPool`](https://golangdoc.github.io/pkg/1.12/crypto/x509/index.html#CertPool). Something similar to what is described [here](https://forfuncsake.github.io/post/2017/08/trust-extra-ca-cert-in-go-app/).

**Comment by viccuad** [comment]
this is complete, closing.
